### ISSUE TITLE
Should this be listed under Omeka S Modules?

### ISSUE THREAD

**Issue by atnjqt** [Daniel-KM/Omeka-S-module-Common#1]
Hi @Daniel-KM, my team is going through a staged installation of Omeka S with SSO integration and we are noticing the `[Common]` module is not among the modules officially supported here: https://omeka.org/s/modules/

Is that expected? There are references for both Guest & Guest Role so thought to reach out and benevolently ask!

**Comment by Daniel-KM** [comment]
Yes, it should. You can submit it yourself, there is no need it should be myself.

**Comment by Daniel-KM** [comment]
The lists on omeka.org are not "officially supported" lists, the moderation is light and anybody can submit anything. You can see the [full list of modules here](https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html). You can submit any of them.
